export const COUNTRIES = [
    "Afghanistan", "Albania", "Algeria", "Andorra", "Angola", "Antigua and Barbuda", "Argentina", "Armenia", "Australia", "Austria", "Azerbaijan",
    "Bahamas", "Bahrain", "Bangladesh", "Barbados", "Belarus", "Belgium", "Belize", "Benin", "Bhutan", "Bolivia", "Bosnia and Herzegovina", "Botswana", "Brazil", "Brunei", "Bulgaria", "Burkina Faso", "Burundi",
    "Cabo Verde", "Cambodia", "Cameroon", "Canada", "Central African Republic", "Chad", "Chile", "China", "Colombia", "Comoros", "Congo (Congo-Brazzaville)", "Costa Rica", "Croatia", "Cuba", "Cyprus", "Czechia (Czech Republic)",
    "Democratic Republic of the Congo", "Denmark", "Djibouti", "Dominica", "Dominican Republic",
    "Ecuador", "Egypt", "El Salvador", "Equatorial Guinea", "Eritrea", "Estonia", "Eswatini (fmr. 'Swaziland')", "Ethiopia",
    "Fiji", "Finland", "France",
    "Gabon", "Gambia", "Georgia", "Germany", "Ghana", "Greece", "Grenada", "Guatemala", "Guinea", "Guinea-Bissau", "Guyana",
    "Haiti", "Holy See", "Honduras", "Hungary",
    "Iceland", "India", "Indonesia", "Iran", "Iraq", "Ireland", "Israel", "Italy", "Ivory Coast",
    "Jamaica", "Japan", "Jordan",
    "Kazakhstan", "Kenya", "Kiribati", "Kuwait", "Kyrgyzstan",
    "Laos", "Latvia", "Lebanon", "Lesotho", "Liberia", "Libya", "Liechtenstein", "Lithuania", "Luxembourg",
    "Madagascar", "Malawi", "Malaysia", "Maldives", "Mali", "Malta", "Marshall Islands", "Mauritania", "Mauritius", "Mexico", "Micronesia", "Moldova", "Monaco", "Mongolia", "Montenegro", "Morocco", "Mozambique", "Myanmar (formerly Burma)",
    "Namibia", "Nauru", "Nepal", "Netherlands", "New Zealand", "Nicaragua", "Niger", "Nigeria", "North Korea", "North Macedonia", "Norway",
    "Oman",
    "Pakistan", "Palau", "Palestine State", "Panama", "Papua New Guinea", "Paraguay", "Peru", "Philippines", "Poland", "Portugal",
    "Qatar",
    "Romania", "Russia", "Rwanda",
    "Saint Kitts and Nevis", "Saint Lucia", "Saint Vincent and the Grenadines", "Samoa", "San Marino", "Sao Tome and Principe", "Saudi Arabia", "Senegal", "Serbia", "Seychelles", "Sierra Leone", "Singapore", "Slovakia", "Slovenia", "Solomon Islands", "Somalia", "South Africa", "South Korea", "South Sudan", "Spain", "Sri Lanka", "Sudan", "Suriname", "Sweden", "Switzerland", "Syria",
    "Tajikistan", "Tanzania", "Thailand", "Timor-Leste", "Togo", "Tonga", "Trinidad and Tobago", "Tunisia", "Turkey", "Turkmenistan", "Tuvalu",
    "Uganda", "Ukraine", "United Arab Emirates", "United Kingdom", "United States of America", "Uruguay", "Uzbekistan",
    "Vanuatu", "Venezuela", "Vietnam",
    "Yemen",
    "Zambia", "Zimbabwe"
];

export const TIMEZONES = [
    { country: "Afghanistan", isoCode: "AF", utcOffset: "UTC+4:30", notes: "Single time zone" },
    { country: "Albania", isoCode: "AL", utcOffset: "UTC+1", notes: "CET" },
    { country: "Algeria", isoCode: "DZ", utcOffset: "UTC+1", notes: "CET" },
    { country: "Andorra", isoCode: "AD", utcOffset: "UTC+1", notes: "CET" },
    { country: "Angola", isoCode: "AO", utcOffset: "UTC+1", notes: "" },
    { country: "Argentina", isoCode: "AR", utcOffset: "UTC-3", notes: "" },
    { country: "Armenia", isoCode: "AM", utcOffset: "UTC+4", notes: "" },
    { country: "Australia", isoCode: "AU", utcOffset: "UTC+8 to UTC+10:30", notes: "Multiple time zones" },
    { country: "Austria", isoCode: "AT", utcOffset: "UTC+1", notes: "" },
    { country: "Azerbaijan", isoCode: "AZ", utcOffset: "UTC+4", notes: "" },
    { country: "Bangladesh", isoCode: "BD", utcOffset: "UTC+6", notes: "" },
    { country: "Belgium", isoCode: "BE", utcOffset: "UTC+1", notes: "" },
    { country: "Bhutan", isoCode: "BT", utcOffset: "UTC+6", notes: "" },
    { country: "Bolivia", isoCode: "BO", utcOffset: "UTC-4", notes: "" },
    { country: "Brazil", isoCode: "BR", utcOffset: "UTC-5 to UTC-2", notes: "Multiple time zones" },
    { country: "Bulgaria", isoCode: "BG", utcOffset: "UTC+2", notes: "" },
    { country: "Cambodia", isoCode: "KH", utcOffset: "UTC+7", notes: "" },
    { country: "Canada", isoCode: "CA", utcOffset: "UTC-8 to UTC-3:30", notes: "Multiple time zones" },
    { country: "China", isoCode: "CN", utcOffset: "UTC+8", notes: "Single official time" },
    { country: "Colombia", isoCode: "CO", utcOffset: "UTC-5", notes: "" },
    { country: "Croatia", isoCode: "HR", utcOffset: "UTC+1", notes: "" },
    { country: "Denmark", isoCode: "DK", utcOffset: "UTC+1", notes: "" },
    { country: "Egypt", isoCode: "EG", utcOffset: "UTC+2", notes: "" },
    { country: "Ethiopia", isoCode: "ET", utcOffset: "UTC+3", notes: "" },
    { country: "Finland", isoCode: "FI", utcOffset: "UTC+2", notes: "" },
    { country: "France", isoCode: "FR", utcOffset: "UTC+1", notes: "" },
    { country: "Germany", isoCode: "DE", utcOffset: "UTC+1", notes: "" },
    { country: "Greece", isoCode: "GR", utcOffset: "UTC+2", notes: "" },
    { country: "Hong Kong", isoCode: "HK", utcOffset: "UTC+8", notes: "" },
    { country: "Hungary", isoCode: "HU", utcOffset: "UTC+1", notes: "" },
    { country: "Iceland", isoCode: "IS", utcOffset: "UTC+0", notes: "" },
    { country: "India", isoCode: "IN", utcOffset: "UTC+5:30", notes: "" },
    { country: "Indonesia", isoCode: "ID", utcOffset: "UTC+7 to UTC+9", notes: "Multiple time zones" },
    { country: "Iran", isoCode: "IR", utcOffset: "UTC+3:30", notes: "" },
    { country: "Ireland", isoCode: "IE", utcOffset: "UTC+0", notes: "" },
    { country: "Israel", isoCode: "IL", utcOffset: "UTC+2", notes: "" },
    { country: "Italy", isoCode: "IT", utcOffset: "UTC+1", notes: "" },
    { country: "Japan", isoCode: "JP", utcOffset: "UTC+9", notes: "" },
    { country: "Kenya", isoCode: "KE", utcOffset: "UTC+3", notes: "" },
    { country: "Kuwait", isoCode: "KW", utcOffset: "UTC+3", notes: "" },
    { country: "Malaysia", isoCode: "MY", utcOffset: "UTC+8", notes: "" },
    { country: "Maldives", isoCode: "MV", utcOffset: "UTC+5", notes: "" },
    { country: "Mexico", isoCode: "MX", utcOffset: "UTC-8 to UTC-5", notes: "Multiple time zones" },
    { country: "Myanmar", isoCode: "MM", utcOffset: "UTC+6:30", notes: "" },
    { country: "Nepal", isoCode: "NP", utcOffset: "UTC+5:45", notes: "Unique offset" },
    { country: "Netherlands", isoCode: "NL", utcOffset: "UTC+1", notes: "" },
    { country: "New Zealand", isoCode: "NZ", utcOffset: "UTC+12", notes: "" },
    { country: "Norway", isoCode: "NO", utcOffset: "UTC+1", notes: "" },
    { country: "Pakistan", isoCode: "PK", utcOffset: "UTC+5", notes: "" },
    { country: "Philippines", isoCode: "PH", utcOffset: "UTC+8", notes: "" },
    { country: "Poland", isoCode: "PL", utcOffset: "UTC+1", notes: "" },
    { country: "Portugal", isoCode: "PT", utcOffset: "UTC+0", notes: "" },
    { country: "Qatar", isoCode: "QA", utcOffset: "UTC+3", notes: "" },
    { country: "Romania", isoCode: "RO", utcOffset: "UTC+2", notes: "" },
    { country: "Russia", isoCode: "RU", utcOffset: "UTC+2 to UTC+12", notes: "11 time zones" },
    { country: "Saudi Arabia", isoCode: "SA", utcOffset: "UTC+3", notes: "" },
    { country: "Singapore", isoCode: "SG", utcOffset: "UTC+8", notes: "" },
    { country: "South Africa", isoCode: "ZA", utcOffset: "UTC+2", notes: "" },
    { country: "South Korea", isoCode: "KR", utcOffset: "UTC+9", notes: "" },
    { country: "Spain", isoCode: "ES", utcOffset: "UTC+1", notes: "" },
    { country: "Sri Lanka", isoCode: "LK", utcOffset: "UTC+5:30", notes: "" },
    { country: "Sweden", isoCode: "SE", utcOffset: "UTC+1", notes: "" },
    { country: "Switzerland", isoCode: "CH", utcOffset: "UTC+1", notes: "" },
    { country: "Thailand", isoCode: "TH", utcOffset: "UTC+7", notes: "" },
    { country: "Turkey", isoCode: "TR", utcOffset: "UTC+3", notes: "" },
    { country: "UAE", isoCode: "AE", utcOffset: "UTC+4", notes: "" },
    { country: "UK", isoCode: "GB", utcOffset: "UTC+0", notes: "" },
    { country: "Ukraine", isoCode: "UA", utcOffset: "UTC+2", notes: "" },
    { country: "USA", isoCode: "US", utcOffset: "UTC-10 to UTC-4", notes: "6 time zones" },
    { country: "Vietnam", isoCode: "VN", utcOffset: "UTC+7", notes: "" }
];

export const CURRENCIES = [
    { code: "INR", name: "Indian Rupee", symbol: "₹" },
    { code: "JPY", name: "Japanese Yen", symbol: "¥" },
    { code: "KES", name: "Kenyan Shilling", symbol: "KSh" },
    { code: "KRW", name: "South Korean Won", symbol: "₩" },
    { code: "KWD", name: "Kuwaiti Dinar", symbol: "د.ك" },
    { code: "LKR", name: "Sri Lankan Rupee", symbol: "Rs" },
    { code: "MAD", name: "Moroccan Dirham", symbol: "dh" },
    { code: "MXN", name: "Mexican Peso", symbol: "$" },
    { code: "MYR", name: "Malaysian Ringgit", symbol: "RM" },
    { code: "NGN", name: "Nigerian Naira", symbol: "₦" },
    { code: "NOK", name: "Norwegian Krone", symbol: "kr" },
    { code: "NPR", name: "Nepali Rupee", symbol: "Rs" },
    { code: "NZD", name: "New Zealand Dollar", symbol: "$" },
    { code: "OMR", name: "Omani Rial", symbol: "ر.ع." },
    { code: "PEN", name: "Peruvian Sol", symbol: "S/" },
    { code: "PHP", name: "Philippine Peso", symbol: "₱" },
    { code: "PKR", name: "Pakistani Rupee", symbol: "Rs" },
    { code: "PLN", name: "Polish Zloty", symbol: "zł" },
    { code: "QAR", name: "Qatari Riyal", symbol: "ر.ق" },
    { code: "RON", name: "Romanian Leu", symbol: "lei" },
    { code: "SAR", name: "Saudi Riyal", symbol: "﷼" },
    { code: "SEK", name: "Swedish Krona", symbol: "kr" },
    { code: "SGD", name: "Singapore Dollar", symbol: "$" },
    { code: "THB", name: "Thai Baht", symbol: "฿" },
    { code: "USD", name: "US Dollar", symbol: "$" },
    { code: "VND", name: "Vietnamese Dong", symbol: "₫" },
    { code: "ZAR", name: "South African Rand", symbol: "R" }
];

export const getCountryFlag = (countryName: string) => {
    const flagMap: Record<string, string> = {
        "Afghanistan": "🇦🇫", "Albania": "🇦🇱", "Algeria": "🇩🇿", "Andorra": "🇦🇩", "Angola": "🇦🇴",
        "Antigua and Barbuda": "🇦🇬", "Argentina": "🇦🇷", "Armenia": "🇦🇲", "Australia": "🇦🇺", "Austria": "🇦🇹",
        "Azerbaijan": "🇦🇿", "Bahamas": "🇧🇸", "Bahrain": "🇧🇭", "Bangladesh": "🇧🇩", "Barbados": "🇧🇧",
        "Belarus": "🇧🇾", "Belgium": "🇧🇪", "Belize": "🇧🇿", "Benin": "🇧🇯", "Bhutan": "🇧🇹",
        "Bolivia": "🇧🇴", "Bosnia and Herzegovina": "🇧🇦", "Botswana": "🇧🇼", "Brazil": "🇧🇷", "Brunei": "🇧🇳",
        "Bulgaria": "🇧🇬", "Burkina Faso": "🇧🇫", "Burundi": "🇧🇮", "Cabo Verde": "🇨🇻", "Cambodia": "🇰🇭",
        "Cameroon": "🇨🇲", "Canada": "🇨🇦", "Central African Republic": "🇨🇫", "Chad": "🇹🇩", "Chile": "🇨🇱",
        "China": "🇨🇳", "Colombia": "🇨🇴", "Comoros": "🇰🇲", "Congo (Congo-Brazzaville)": "🇨🇬", "Costa Rica": "🇨🇷",
        "Croatia": "🇭🇷", "Cuba": "🇨🇺", "Cyprus": "🇨🇾", "Czechia (Czech Republic)": "🇨🇿",
        "Democratic Republic of the Congo": "🇨🇩", "Denmark": "🇩🇰", "Djibouti": "🇩🇯", "Dominica": "🇩🇲",
        "Dominican Republic": "🇩🇴", "Ecuador": "🇪🇨", "Egypt": "🇪🇬", "El Salvador": "🇸🇻", "Equatorial Guinea": "🇬🇶",
        "Eritrea": "🇪🇷", "Estonia": "🇪🇪", "Eswatini (fmr. 'Swaziland')": "🇸🇿", "Ethiopia": "🇪🇹", "Fiji": "🇫🇯",
        "Finland": "🇫🇮", "France": "🇫🇷", "Gabon": "🇬🇦", "Gambia": "🇬🇲", "Georgia": "🇬🇪", "Germany": "🇩🇪",
        "Ghana": "🇬🇭", "Greece": "🇬🇷", "Grenada": "🇬🇩", "Guatemala": "🇬🇹", "Guinea": "🇬🇳", "Guinea-Bissau": "🇬🇼",
        "Guyana": "🇬🇾", "Haiti": "🇭🇹", "Holy See": "🇻🇦", "Honduras": "🇭🇳", "Hungary": "🇭🇺", "Iceland": "🇮🇸",
        "India": "🇮🇳", "Indonesia": "🇮🇩", "Iran": "🇮🇷", "Iraq": "🇮🇶", "Ireland": "🇮🇪", "Israel": "🇮🇱",
        "Italy": "🇮🇹", "Ivory Coast": "🇨🇮", "Jamaica": "🇯🇲", "Japan": "🇯🇵", "Jordan": "🇯🇴", "Kazakhstan": "🇰🇿",
        "Kenya": "🇰🇪", "Kiribati": "🇰🇮", "Kuwait": "🇰🇼", "Kyrgyzstan": "🇰🇬", "Laos": "🇱🇦", "Latvia": "🇱🇻",
        "Lebanon": "🇱🇧", "Lesotho": "🇱🇸", "Liberia": "🇱🇷", "Libya": "🇱🇾", "Liechtenstein": "🇱🇮", "Lithuania": "🇱🇹",
        "Luxembourg": "🇱🇺", "Madagascar": "🇲🇬", "Malawi": "🇲🇼", "Malaysia": "🇲🇾", "Maldives": "🇲🇻", "Mali": "🇲🇱",
        "Malta": "🇲🇹", "Marshall Islands": "🇲🇭", "Mauritania": "🇲🇷", "Mauritius": "🇲🇺", "Mexico": "🇲🇽",
        "Micronesia": "🇫🇲", "Moldova": "🇲🇩", "Monaco": "🇲🇨", "Mongolia": "🇲🇳", "Montenegro": "🇲🇪", "Morocco": "🇲🇦",
        "Mozambique": "🇲🇿", "Myanmar (formerly Burma)": "🇲🇲", "Namibia": "🇳🇦", "Nauru": "🇳🇷", "Nepal": "🇳🇵",
        "Netherlands": "🇳🇱", "New Zealand": "🇳🇿", "Nicaragua": "🇳🇮", "Niger": "🇳🇪", "Nigeria": "🇳🇬",
        "North Korea": "🇰🇵", "North Macedonia": "🇲🇰", "Norway": "🇳🇴", "Oman": "🇴🇲", "Pakistan": "🇵🇰", "Palau": "🇵🇼",
        "Palestine State": "🇵🇸", "Panama": "🇵🇦", "Papua New Guinea": "🇵🇬", "Paraguay": "🇵🇾", "Peru": "🇵🇪",
        "Philippines": "🇵🇭", "Poland": "🇵🇱", "Portugal": "🇵🇹", "Qatar": "🇶🇦", "Romania": "🇷🇴", "Russia": "🇷🇺",
        "Rwanda": "🇷🇼", "Saint Kitts and Nevis": "🇰🇳", "Saint Lucia": "🇱🇨", "Saint Vincent and the Grenadines": "🇻🇨",
        "Samoa": "🇼🇸", "San Marino": "🇸🇲", "Sao Tome and Principe": "🇸🇹", "Saudi Arabia": "🇸🇦", "Senegal": "🇸🇳",
        "Serbia": "🇷🇸", "Seychelles": "🇸🇨", "Sierra Leone": "🇸🇱", "Singapore": "🇸🇬", "Slovakia": "🇸🇰",
        "Slovenia": "🇸🇮", "Solomon Islands": "🇸🇧", "Somalia": "🇸🇴", "South Africa": "🇿🇦", "South Korea": "🇰🇷",
        "South Sudan": "🇸🇸", "Spain": "🇪🇸", "Sri Lanka": "🇱🇰", "Sudan": "🇸🇩", "Suriname": "🇸🇷", "Sweden": "🇸🇪",
        "Switzerland": "🇨🇭", "Syria": "🇸🇾", "Tajikistan": "🇹🇯", "Tanzania": "🇹🇿", "Thailand": "🇹🇭",
        "Timor-Leste": "🇹🇱", "Togo": "🇹🇬", "Tonga": "🇹🇴", "Trinidad and Tobago": "🇹🇹", "Tunisia": "🇹🇳",
        "Turkey": "🇹🇷", "Turkmenistan": "🇹🇲", "Tuvalu": "🇹🇻", "Uganda": "🇺🇬", "Ukraine": "🇺🇦",
        "United Arab Emirates": "🇦🇪", "United Kingdom": "🇬🇧", "United States of America": "🇺🇸", "Uruguay": "🇺🇾",
        "Uzbekistan": "🇺🇿", "Vanuatu": "🇻🇺", "Venezuela": "🇻🇪", "Vietnam": "🇻🇳", "Yemen": "🇾🇪",
        "Zambia": "🇿🇲", "Zimbabwe": "🇿🇼"
    };

    return flagMap[countryName] || "🌍";
};
